/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiLogsRouteImport } from './routes/ai-logs'
import { Route as AppDownloadRouteImport } from './routes/app-download'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as DailyTasksRouteImport } from './routes/daily-tasks'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MerchantListRouteImport } from './routes/merchant-list'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ReportImportsRouteImport } from './routes/report-imports'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApiAutomationWorkerRouteImport } from './routes/api.automation-worker'
import { Route as ApiMeetingNotificationsRouteImport } from './routes/api.meeting-notifications'
import { Route as ApiMoniecrmWorkerRouteImport } from './routes/api.moniecrm-worker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLogsRoute = AiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDownloadRoute = AppDownloadRouteImport.update({
  id: '/app-download',
  path: '/app-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyTasksRoute = DailyTasksRouteImport.update({
  id: '/daily-tasks',
  path: '/daily-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantListRoute = MerchantListRouteImport.update({
  id: '/merchant-list',
  path: '/merchant-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportImportsRoute = ReportImportsRouteImport.update({
  id: '/report-imports',
  path: '/report-imports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationWorkerRoute = ApiAutomationWorkerRouteImport.update({
  id: '/api/automation-worker',
  path: '/api/automation-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingNotificationsRoute = ApiMeetingNotificationsRouteImport.update({
  id: '/api/meeting-notifications',
  path: '/api/meeting-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoniecrmWorkerRoute = ApiMoniecrmWorkerRouteImport.update({
  id: '/api/moniecrm-worker',
  path: '/api/moniecrm-worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/app-download': typeof AppDownloadRoute
  '/automation': typeof AutomationRoute
  '/daily-tasks': typeof DailyTasksRoute
  '/meetings': typeof MeetingsRoute
  '/merchant-list': typeof MerchantListRoute
  '/readiness': typeof ReadinessRoute
  '/report-imports': typeof ReportImportsRoute
  '/staff': typeof StaffRoute
  '/api/automation-worker': typeof ApiAutomationWorkerRoute
  '/api/meeting-notifications': typeof ApiMeetingNotificationsRoute
  '/api/moniecrm-worker': typeof ApiMoniecrmWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/app-download': typeof AppDownloadRoute
  '/automation': typeof AutomationRoute
  '/daily-tasks': typeof DailyTasksRoute
  '/meetings': typeof MeetingsRoute
  '/merchant-list': typeof MerchantListRoute
  '/readiness': typeof ReadinessRoute
  '/report-imports': typeof ReportImportsRoute
  '/staff': typeof StaffRoute
  '/api/automation-worker': typeof ApiAutomationWorkerRoute
  '/api/meeting-notifications': typeof ApiMeetingNotificationsRoute
  '/api/moniecrm-worker': typeof ApiMoniecrmWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/app-download': typeof AppDownloadRoute
  '/automation': typeof AutomationRoute
  '/daily-tasks': typeof DailyTasksRoute
  '/meetings': typeof MeetingsRoute
  '/merchant-list': typeof MerchantListRoute
  '/readiness': typeof ReadinessRoute
  '/report-imports': typeof ReportImportsRoute
  '/staff': typeof StaffRoute
  '/api/automation-worker': typeof ApiAutomationWorkerRoute
  '/api/meeting-notifications': typeof ApiMeetingNotificationsRoute
  '/api/moniecrm-worker': typeof ApiMoniecrmWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-logs'
    | '/app-download'
    | '/automation'
    | '/daily-tasks'
    | '/meetings'
    | '/merchant-list'
    | '/readiness'
    | '/report-imports'
    | '/staff'
    | '/api/automation-worker'
    | '/api/meeting-notifications'
    | '/api/moniecrm-worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-logs'
    | '/app-download'
    | '/automation'
    | '/daily-tasks'
    | '/meetings'
    | '/merchant-list'
    | '/readiness'
    | '/report-imports'
    | '/staff'
    | '/api/automation-worker'
    | '/api/meeting-notifications'
    | '/api/moniecrm-worker'
  id:
    | '__root__'
    | '/'
    | '/ai-logs'
    | '/app-download'
    | '/automation'
    | '/daily-tasks'
    | '/meetings'
    | '/merchant-list'
    | '/readiness'
    | '/report-imports'
    | '/staff'
    | '/api/automation-worker'
    | '/api/meeting-notifications'
    | '/api/moniecrm-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLogsRoute: typeof AiLogsRoute
  AppDownloadRoute: typeof AppDownloadRoute
  AutomationRoute: typeof AutomationRoute
  DailyTasksRoute: typeof DailyTasksRoute
  MeetingsRoute: typeof MeetingsRoute
  MerchantListRoute: typeof MerchantListRoute
  ReadinessRoute: typeof ReadinessRoute
  ReportImportsRoute: typeof ReportImportsRoute
  StaffRoute: typeof StaffRoute
  ApiAutomationWorkerRoute: typeof ApiAutomationWorkerRoute
  ApiMeetingNotificationsRoute: typeof ApiMeetingNotificationsRoute
  ApiMoniecrmWorkerRoute: typeof ApiMoniecrmWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-logs': {
      id: '/ai-logs'
      path: '/ai-logs'
      fullPath: '/ai-logs'
      preLoaderRoute: typeof AiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-download': {
      id: '/app-download'
      path: '/app-download'
      fullPath: '/app-download'
      preLoaderRoute: typeof AppDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-tasks': {
      id: '/daily-tasks'
      path: '/daily-tasks'
      fullPath: '/daily-tasks'
      preLoaderRoute: typeof DailyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-list': {
      id: '/merchant-list'
      path: '/merchant-list'
      fullPath: '/merchant-list'
      preLoaderRoute: typeof MerchantListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-imports': {
      id: '/report-imports'
      path: '/report-imports'
      fullPath: '/report-imports'
      preLoaderRoute: typeof ReportImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automation-worker': {
      id: '/api/automation-worker'
      path: '/api/automation-worker'
      fullPath: '/api/automation-worker'
      preLoaderRoute: typeof ApiAutomationWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meeting-notifications': {
      id: '/api/meeting-notifications'
      path: '/api/meeting-notifications'
      fullPath: '/api/meeting-notifications'
      preLoaderRoute: typeof ApiMeetingNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moniecrm-worker': {
      id: '/api/moniecrm-worker'
      path: '/api/moniecrm-worker'
      fullPath: '/api/moniecrm-worker'
      preLoaderRoute: typeof ApiMoniecrmWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLogsRoute: AiLogsRoute,
  AppDownloadRoute: AppDownloadRoute,
  AutomationRoute: AutomationRoute,
  DailyTasksRoute: DailyTasksRoute,
  MeetingsRoute: MeetingsRoute,
  MerchantListRoute: MerchantListRoute,
  ReadinessRoute: ReadinessRoute,
  ReportImportsRoute: ReportImportsRoute,
  StaffRoute: StaffRoute,
  ApiAutomationWorkerRoute: ApiAutomationWorkerRoute,
  ApiMeetingNotificationsRoute: ApiMeetingNotificationsRoute,
  ApiMoniecrmWorkerRoute: ApiMoniecrmWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
