import type { TaskStatus, TaskType } from "../../../src/domain/models";

import { supabase } from "./supabase";

export interface DirectorAssistantOption {
  id: string;
  fullName: string;
}

export interface DirectorMerchantOption {
  id: string;
  businessName: string;
  phoneNumber: string | null;
  accountNumber: string | null;
  isActive: boolean;
  terminals: DirectorTerminalOption[];
}

export interface DirectorTerminalOption {
  id: string;
  terminalId: string;
  serialNumber: string | null;
  merchantId: string | null;
}

export interface DirectorTaskQueueItem {
  id: string;
  taskDate: string;
  taskType: TaskType;
  status: TaskStatus;
  priority: number;
  merchantId: string | null;
  terminalId: string | null;
  assignedTo: string;
  reason: string;
  recommendedTalkingPoints: string | null;
  dueAt: string | null;
  queueRank: number | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  merchant: DirectorMerchantOption | null;
  terminal: DirectorTerminalOption | null;
  assistant: DirectorAssistantOption | null;
}

export interface DirectorAssignmentWorkspace {
  date: string;
  assistants: DirectorAssistantOption[];
  merchants: DirectorMerchantOption[];
  tasks: DirectorTaskQueueItem[];
}

export interface CreateDirectorTaskInput {
  directorId: string;
  taskDate: string;
  taskType: TaskType;
  priority: number;
  merchantId: string;
  terminalId: string | null;
  assistantId: string;
  reason: string;
}

export interface AssignmentMutationResult {
  duplicate: boolean;
  taskId: string;
}

const ACTIVE_TASK_STATUSES: TaskStatus[] = ["assigned", "in_progress", "postponed"];

export async function loadDirectorAssignmentWorkspace(
  date = lagosDateKey(),
): Promise<DirectorAssignmentWorkspace> {
  const [assistantResult, merchantResult, terminalResult, taskResult] = await Promise.all([
    supabase
      .from("profiles")
      .select("id,full_name,role,is_active")
      .eq("role", "assistant")
      .eq("is_active", true)
      .order("full_name", { ascending: true }),
    supabase
      .from("merchants")
      .select("id,business_name,phone_number,account_number,is_active")
      .eq("is_active", true)
      .order("business_name", { ascending: true })
      .limit(1000),
    supabase
      .from("terminals")
      .select("id,terminal_id,serial_number,merchant_id")
      .order("terminal_id", { ascending: true })
      .limit(1500),
    supabase
      .from("tasks")
      .select(
        "id,task_date,task_type,status,priority,merchant_id,terminal_id,assigned_to,reason,recommended_talking_points,due_at,queue_rank,auto_generated,created_at,updated_at",
      )
      .eq("task_date", date)
      .order("queue_rank", { ascending: true })
      .order("priority", { ascending: false })
      .order("created_at", { ascending: true })
      .limit(250),
  ]);

  if (assistantResult.error) throw assistantResult.error;
  if (merchantResult.error) throw merchantResult.error;
  if (terminalResult.error) throw terminalResult.error;
  if (taskResult.error) throw taskResult.error;

  const assistants: DirectorAssistantOption[] = (assistantResult.data ?? []).map((row) => ({
    id: row.id,
    fullName: row.full_name,
  }));

  const terminals: DirectorTerminalOption[] = (terminalResult.data ?? []).map((row) => ({
    id: row.id,
    terminalId: row.terminal_id,
    serialNumber: blankToNull(row.serial_number),
    merchantId: row.merchant_id,
  }));

  const terminalsByMerchant = new Map<string, DirectorTerminalOption[]>();
  for (const terminal of terminals) {
    if (!terminal.merchantId) continue;
    const current = terminalsByMerchant.get(terminal.merchantId) ?? [];
    current.push(terminal);
    terminalsByMerchant.set(terminal.merchantId, current);
  }

  const merchants: DirectorMerchantOption[] = (merchantResult.data ?? []).map((row) => ({
    id: row.id,
    businessName: row.business_name?.trim() || "Business name not available",
    phoneNumber: blankToNull(row.phone_number),
    accountNumber: blankToNull(row.account_number),
    isActive: Boolean(row.is_active),
    terminals: terminalsByMerchant.get(row.id) ?? [],
  }));

  const merchantMap = new Map(merchants.map((merchant) => [merchant.id, merchant] as const));
  const terminalMap = new Map(terminals.map((terminal) => [terminal.id, terminal] as const));
  const assistantMap = new Map(assistants.map((assistant) => [assistant.id, assistant] as const));

  const tasks: DirectorTaskQueueItem[] = (taskResult.data ?? []).map((row) => ({
    id: row.id,
    taskDate: row.task_date,
    taskType: row.task_type as TaskType,
    status: row.status as TaskStatus,
    priority: Number(row.priority),
    merchantId: row.merchant_id,
    terminalId: row.terminal_id,
    assignedTo: row.assigned_to,
    reason: row.reason,
    recommendedTalkingPoints: blankToNull(row.recommended_talking_points),
    dueAt: row.due_at,
    queueRank: row.queue_rank === null ? null : Number(row.queue_rank),
    autoGenerated: Boolean(row.auto_generated),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    merchant: row.merchant_id ? merchantMap.get(row.merchant_id) ?? null : null,
    terminal: row.terminal_id ? terminalMap.get(row.terminal_id) ?? null : null,
    assistant: assistantMap.get(row.assigned_to) ?? null,
  }));

  return { date, assistants, merchants, tasks };
}

export async function createDirectorTask(
  input: CreateDirectorTaskInput,
): Promise<AssignmentMutationResult> {
  const reason = input.reason.trim();
  if (!reason) throw new Error("A reason is required before assigning a task.");
  if (input.priority < 1 || input.priority > 5) {
    throw new Error("Priority must be between 1 and 5.");
  }

  const duplicate = await findDuplicateActiveAssignment({
    taskDate: input.taskDate,
    taskType: input.taskType,
    merchantId: input.merchantId,
    terminalId: input.terminalId,
    assistantId: input.assistantId,
  });
  if (duplicate) return { duplicate: true, taskId: duplicate.id };

  const { data, error } = await supabase
    .from("tasks")
    .insert({
      task_date: input.taskDate,
      task_type: input.taskType,
      status: "assigned",
      priority: input.priority,
      merchant_id: input.merchantId,
      terminal_id: input.terminalId,
      assigned_to: input.assistantId,
      reason,
      recommended_talking_points: null,
      due_at: null,
      created_by: input.directorId,
      auto_generated: false,
      queue_rank: null,
    })
    .select("id")
    .single();

  if (error) throw error;

  return { duplicate: false, taskId: data.id };
}

export async function reassignDirectorTask(
  task: DirectorTaskQueueItem,
  newAssistantId: string,
): Promise<AssignmentMutationResult> {
  if (task.assignedTo === newAssistantId) {
    return { duplicate: true, taskId: task.id };
  }
  if (task.status !== "assigned") {
    throw new Error("Only untouched tasks in Assigned status can be reassigned.");
  }

  const duplicate = await findDuplicateActiveAssignment({
    taskDate: task.taskDate,
    taskType: task.taskType,
    merchantId: task.merchantId,
    terminalId: task.terminalId,
    assistantId: newAssistantId,
    excludeTaskId: task.id,
  });
  if (duplicate) return { duplicate: true, taskId: duplicate.id };

  const { data, error } = await supabase
    .from("tasks")
    .update({ assigned_to: newAssistantId, queue_rank: null })
    .eq("id", task.id)
    .eq("status", "assigned")
    .select("id")
    .maybeSingle();

  if (error) throw error;
  if (!data) {
    throw new Error("The task changed before reassignment. Refresh the queue and try again.");
  }

  return { duplicate: false, taskId: data.id };
}

async function findDuplicateActiveAssignment(input: {
  taskDate: string;
  taskType: TaskType;
  merchantId: string | null;
  terminalId: string | null;
  assistantId: string;
  excludeTaskId?: string;
}) {
  let query = supabase
    .from("tasks")
    .select("id")
    .eq("task_date", input.taskDate)
    .eq("task_type", input.taskType)
    .eq("assigned_to", input.assistantId)
    .in("status", ACTIVE_TASK_STATUSES)
    .limit(1);

  query = input.merchantId ? query.eq("merchant_id", input.merchantId) : query.is("merchant_id", null);
  query = input.terminalId ? query.eq("terminal_id", input.terminalId) : query.is("terminal_id", null);
  if (input.excludeTaskId) query = query.neq("id", input.excludeTaskId);

  const { data, error } = await query.maybeSingle();
  if (error) throw error;
  return data;
}

export function canDirectorReassignTask(task: DirectorTaskQueueItem) {
  return task.status === "assigned";
}

export function lagosDateKey(date = new Date()) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Africa/Lagos",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

function blankToNull(value: string | null | undefined) {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}
